### ISSUE TITLE
Broken with node tls module: Cannot read property '1' of null

### ISSUE THREAD

**Issue by binki** [nodegit/promisify-node#25]
```
> require('promisify-node')('tls');
TypeError: Cannot read property '1' of null
    at module.exports (/home/ohnobinki/public_html/ohnopub-status/node_modules/promisify-node/utils/args.js:9:63)
    at processExports (/home/ohnobinki/public_html/ohnopub-status/node_modules/promisify-node/index.js:61:29)
    at /home/ohnobinki/public_html/ohnopub-status/node_modules/promisify-node/index.js:137:23
    at Array.forEach (native)
    at processExports (/home/ohnobinki/public_html/ohnopub-status/node_modules/promisify-node/index.js:132:6)
    at module.exports (/home/ohnobinki/public_html/ohnopub-status/node_modules/promisify-node/index.js:164:10)
    at repl:1:26
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
```

```
ohnobinki@gibby ~/public_html/ohnopub-status $ grep -e version node_modules/promisify-node/package.json
  "version": "0.4.0"
ohnobinki@gibby ~/public_html/ohnopub-status $ node --version
v7.0.0
```

**Comment by tbranyen** [comment]
Fixed in #02fc47c
